### ISSUE TITLE
Cannot retrieve vendor options

### ISSUE THREAD

**Issue by los93sol** [garysharp/DhcpServerApi#3]
It appears DhcpEnumOptionsV5 must be implemented to retrieve custom vendor options.  Interestingly, I can see the vendors options defined in the server classes, but was unable to find a way to access them.

**Comment by garysharp** [comment]
Happy to implement DhcpEnumOptionsV5 (and related APIs).

Before I do, I appreciate a little more input.
Can you provide an example of what you think our API should look like?
How would you want to retrieve the custom vendor options?
Possibly a little information around your use-case might be useful also.

**Comment by los93sol** [comment]
I slapped together a very quick and dirty implementation of just DhcpEnumOptionsV5 just as a test.

I ended up with something like this.....

var dhcpServer = DhcpServer.Connect(ip);
var vOption = dhcpServer.GetVendorOptions(vendorName);

It seems like it makes more sense to implement similar to the options that go against the default user and vendor classes though where you could do something like...

var vOption = dhcpServer.GetVendorOptions(vendorName);
var vOption = dhcpServer.GetVendorOption(vendorName, optionId);

or

foreach (var scope in dhcpServer.Scopes.ToList())
{
    var vOption = scope.VendorOptionValues(vendorName);
}

We use a custom vendor option for configuring certain devices, basically I'm just looking to retrieve that value systemically so that I can do some validation against the content.

If you'd like I can fork the repo and submit a PR with the implementation that I have now, but fair warning it is not pretty nor do I think it's correct by any means, I just stuck it together to see if the V5 API would even provide the values I was looking for.

**Comment by garysharp** [comment]
Great info - thanks! That really helps understand the problem better.

The API we currently have roughly follows the style of every object being enumerable, rather than being looked up. The intent is to encourage discoverability and reduce the requirement to know special strings. One example is that we don't require specifying the [servers name/IP](https://github.com/garysharp/DhcpServerApi/blob/c8ab75e9721818a4c401232871bf0aa4d2c56cd9/src/Dhcp/DhcpServer.cs#L154). There are situations where this is best though (such as explicitly specifying a server name because of invalid entries (ie. decommissioned server) in the directory which cause errors when enumerating servers).

We might need to have some additional properties on DhcpServerClass, and a few new objects to try and continue the API style. I'll give this a bit more thought.

If you've got any working code send it through, it doesn't matter what quality it is, it will probably save me time. But don't feel compelled to put together anything to formal.

1:00 AM for me now, I'll pick this up tomorrow.

**Comment by los93sol** [comment]
I agree that not needing to know special strings is the ideal implementation.  One thing I noticed was that when I iterate the classes the vendor options show up there, albeit without values, but I believe the classes where isVendor == true might be the special strings that would allow you to stick with the enumerable model that the rest of the API follows.  I have quite a bit on my plate atm, but I'll try to get something together this afternoon in the form of a PR.

**Comment by garysharp** [comment]
I've done some work to provide support for User and Vendor Classes. Let me know what you think and we'll go from there.

**Comment by los93sol** [comment]
Thanks for getting something in place so quickly!  It looks good, I like the way option values are now associated to the classes as well.  The structure of server level options looks good too!  The one thing I did notice was the when iterating custom vendor options from the scope like scope.AllOptionValues.ToList() the custom vendor options exist in the list there but throws an exception when iterating in the DhcpDemo program.

**Comment by garysharp** [comment]
Good pickup - identified and hopefully fixed in 84541836e594ef236a77c3731f88698fc554d850

Let me know if it meets the needs of this issue or it needs more work.

**Comment by los93sol** [comment]
Very nice, looks like that got it!  Thank you so much for your help with this!
